export function collectWorkshopNodes(overlay) {
  const query = selector => overlay.querySelector(selector);
  const queryAll = selector => [...overlay.querySelectorAll(selector)];
  return {
    health: query('[data-role="health"]'),
    account: query('[data-role="account"]'),
    accountWrap: query('[data-role="account-wrap"]'),
    accountMenu: query('[data-role="account-menu"]'),
    login: query('[data-action="login"]'),
    logout: query('[data-action="logout"]'),
    adminTab: query('[data-action="admin-menu"]'),
    discoverHeadTools: query('[data-role="discover-head-tools"]'),
    search: query('[data-field="search"]'),
    category: query('[data-field="category"]'),
    tag: query('[data-field="tag"]'),
    sort: query('[data-field="sort"]'),
    discoverCategories: queryAll('[data-category-filter]'),
    discoverMore: query('[data-action="discover-more"]'),
    discoverCount: query('[data-role="discover-count"]'),
    discoverList: query('[data-role="discover-list"]'),
    installedList: query('[data-role="installed-list"]'),
    offlineInput: query('[data-action="import-offline"]'),
    checkAllUpdates: query('[data-action="check-all-updates"]'),
    storageManager: query('[data-action="storage-manager"]'),
    myList: query('[data-role="my-list"]'),
    pendingList: query('[data-role="pending-list"]'),
    adminSearch: query('[data-field="admin-search"]'),
    adminStatus: query('[data-field="admin-status"]'),
    adminCategory: query('[data-field="admin-category"]'),
    adminSearchButton: query('[data-action="admin-search"]'),
    adminReportRefreshButton: query('[data-action="admin-report-refresh"]'),
    adminUserSearchButton: query('[data-action="admin-user-search"]'),
    adminViewButtons: queryAll('[data-admin-view]'),
    adminSections: queryAll('[data-admin-section]'),
    reportStatus: query('[data-field="admin-report-status"]'),
    reportList: query('[data-role="report-list"]'),
    userSearch: query('[data-field="admin-user-search"]'),
    userBanned: query('[data-field="admin-user-banned"]'),
    userList: query('[data-role="user-list"]'),
    createForm: query('[data-form="create-project"]'),
    createVersion: query('[data-field="create-version"]'),
    createCover: query('[data-field="create-cover"]'),
    createVersionState: query('[data-role="create-version-state"]'),
    createArtifactList: query('[data-role="create-artifact-list"]'),
    createCoverState: query('[data-role="create-cover-state"]'),
    createCoverPreview: query('[data-role="create-cover-preview"]'),
  };
}
