export function createWorkshopBridge({
  version,
  open,
  close,
  refresh,
  destroy,
  hotUpdate,
  workshopApi,
  projectService,
  selfUpdater,
}) {
  return {
    version, open, close, refresh, destroy, hotUpdate,
    login: () => workshopApi.login(),
    logout: () => workshopApi.logout(),
    getSession: () => workshopApi.getStoredAuth(),
    listInstalled: () => projectService.installed(),
    cacheProject: projectId => projectService.cache(projectId),
    checkProjectUpdate: projectId => projectService.checkUpdate(projectId),
    checkAllProjectUpdates: force => projectService.checkAllUpdates(Boolean(force)),
    preflightProject: projectId => projectService.preflight(projectId),
    applyProject: projectId => projectService.apply(projectId),
    inspectProjectInstallation: projectId => projectService.inspectInstallation(projectId),
    repairProjectInstallation: projectId => projectService.repair(projectId),
    uninstallProject: projectId => projectService.uninstall(projectId),
    exportProject: projectId => projectService.exportCached(projectId),
    importProject: file => projectService.importOffline(file),
    getStorageEstimate: () => projectService.storageEstimate(),
    cleanupCachedProjects: () => projectService.cleanupCacheOnly(),
    checkWorkshopUpdate: () => selfUpdater.check(),
    updateWorkshopLoaderLink: () => selfUpdater.updateLoaderLink(),
  };
}
