package define


const (
	ERRCODE_SUCCESS 		= 0		// 统一成功代码
	ERRCODE_CACHE_DATABASE  = 100	// DB操作失败

	MATCH_INVITED_TIMEOUT 	= 8001 	// 超时无人响应
	MATCH_INVITED_CLOSE 	= 8002  // 邀请取消
	MATCH_INVITED_REFUE 	= 8003 	// 邀请被拒绝
	MATCH_INVITED_OVERDUE  	= 8004 	// 邀请过期
	MATCH_INVITED_FINISH 	= 8005 	// 邀请已结束
	MATCH_INVITED_NEWBIE 	= 8006 	// 被邀新手

	REDEEM_CODE_NO_FIND 	= 9001	// 找不到兑换数据
	REDEEM_CODE_HAS_USED 	= 9002	// 玩家已经领取
	REDEEM_CODE_INVALID		= 9003  // 兑换码已经失效
	REDEEM_CODE_USE_TIME	= 9004  // 兑换码已经领完
	REDEEM_CODE_NO_BEGIN	= 9005  // 兑换码还没开放

	ACHIEVEMENT_REQUEST_ID  = 9101 	// 错误的成就ID
	ACHIEVEMENT_NOT_FINISH  = 9102 	// 成就还未完成
	ACHIEVEMENT_HAS_TAKED   = 9103 	// 奖励已经领取
	ACHIEVEMENT_NOT_ENOUGH  = 9104 	// 成就点不够
	ACHIEVEMENT_POINT_VALUE = 9105 	// 错误的成就点
	ACHIEVEMENT_POINT_TAKED = 9106 	// 成就点已领取

	OTHERGAME_SHARED		= 9201 	// 已经分享过
	OTHERGAME_NO_SHARE		= 9202  // 未分享游戏
	OTHERGAME_NO_GAMEID 	= 9203 	// 没有这个游戏
	OTHERGAME_REWARD_GET	= 9204	// 奖励已领取
)
