#!/usr/bin/env python3
"""Build calculator delivery script.

calculator follows the same delivery model as world engine and status bar:
src/Calculator -> script/辅助计算脚本.js
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'src' / 'Calculator'
OUT = ROOT / 'script' / '辅助计算脚本.js'
HEADER = '// Generated by tools/build-calculator.py. Do not edit directly.\n'


def merged():
    return HEADER + '\n\n'.join(
        p.read_text(encoding='utf-8')
        for p in sorted(SRC.rglob('*.part.js'))
    )


def main():
    import sys
    if not SRC.exists():
        raise SystemExit('missing src/Calculator')
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding='utf-8') != merged():
            raise SystemExit('calculator delivery out of sync')
        return
    OUT.write_text(merged(), encoding='utf-8')


if __name__ == '__main__':
    main()
